services:
  airflow-init:
    build: .
    image: cs611-as02-loan-default:latest
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__FERNET_KEY=PAqBeGJLJTYFzVkOGHWIYXdLO7XdXz5yTdxAGJe9ezM=
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - PIPELINE_ROOT=/opt/airflow
      - PIPELINE_SCRIPTS=/opt/airflow/scripts
      - PYTHONPATH=/opt/airflow:/opt/airflow/scripts
    volumes:
      - airflow_data:/opt/airflow
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./utils:/opt/airflow/utils
    entrypoint: >
      /bin/bash -c "airflow db migrate &&
      airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com || true"

  airflow-webserver:
    build: .
    image: cs611-as02-loan-default:latest
    depends_on:
      - airflow-init
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__FERNET_KEY=PAqBeGJLJTYFzVkOGHWIYXdLO7XdXz5yTdxAGJe9ezM=
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - PIPELINE_ROOT=/opt/airflow
      - PIPELINE_SCRIPTS=/opt/airflow/scripts
      - PYTHONPATH=/opt/airflow:/opt/airflow/scripts
    volumes:
      - airflow_data:/opt/airflow
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./utils:/opt/airflow/utils
    ports:
      - "8080:8080"
    command: webserver
    restart: always

  airflow-scheduler:
    build: .
    image: cs611-as02-loan-default:latest
    depends_on:
      - airflow-init
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__FERNET_KEY=PAqBeGJLJTYFzVkOGHWIYXdLO7XdXz5yTdxAGJe9ezM=
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - PIPELINE_ROOT=/opt/airflow
      - PIPELINE_SCRIPTS=/opt/airflow/scripts
      - PYTHONPATH=/opt/airflow:/opt/airflow/scripts
    volumes:
      - airflow_data:/opt/airflow
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./utils:/opt/airflow/utils
    command: scheduler
    restart: always

volumes:
  airflow_data:
